---
- name: Instalar e configurar o agente RustDesk em máquinas Windows
  hosts: windows
  tasks:
    - name: Baixar o instalador do RustDesk
      win_get_url:
        url: "https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-x86_64.exe"
        dest: "C:\\Temp\\rustdesk.exe"

    - name: Instalar o RustDesk
      win_package:
        path: "C:\\Temp\\rustdesk.exe"
        arguments: "--silent-install"
        state: present

    - name: Parar o serviço RustDesk
      win_service:
        name: RustDesk
        state: stopped

    - name: Remover arquivo de configuração existente do RustDesk para o usuário atual
      win_file:
        path: "C:\\Users\\{{ ansible_user }}\\AppData\\Roaming\\RustDesk\\config\\RustDesk2.toml"
        state: absent

    - name: Criar novo arquivo de configuração do RustDesk para o usuário atual
      win_template:
        src: rustdesk_config.j2
        dest: "C:\\Users\\{{ ansible_user }}\\AppData\\Roaming\\RustDesk\\config\\RustDesk2.toml"

    - name: Remover arquivo de configuração existente do RustDesk para o serviço local
      win_file:
        path: "C:\\Windows\\ServiceProfiles\\LocalService\\AppData\\Roaming\\RustDesk\\config\\RustDesk2.toml"
        state: absent

    - name: Criar novo arquivo de configuração do RustDesk para o serviço local
      win_template:
        src: rustdesk_config.j2
        dest: "C:\\Windows\\ServiceProfiles\\LocalService\\AppData\\Roaming\\RustDesk\\config\\RustDesk2.toml"

    - name: Iniciar o serviço RustDesk
      win_service:
        name: RustDesk
        state: started

    - name: Configurar a senha do RustDesk e mascará-la
      win_shell: |
        $password = "Teste12345"
        $hashedPassword = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($password))
        Start-Process "$env:ProgramFiles\\RustDesk\\RustDesk.exe" -ArgumentList "--password $password" -Wait
        net stop RustDesk
        Stop-Process -Name RustDesk -Force

        # Atualizar o arquivo de configuração com a senha mascarada
        $configPathUser = "C:\\Users\\{{ ansible_user }}\\AppData\\Roaming\\RustDesk\\config\\RustDesk2.toml"
        $configPathService

