---
- name: Instalar e configurar RustDesk
  hosts: windows
  tasks:
    - name: Baixar o RustDesk
      win_get_url:
        url: "https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-x86_64.exe"
        dest: "C:\\Temp\\rustdesk.exe"

    - name: Instalar o RustDesk
      win_package:
        path: "C:\\Temp\\rustdesk.exe"
        arguments: "/silent"
        state: present

    - name: Parar o serviço RustDesk
      win_service:
        name: "RustDesk"
        state: stopped
      ignore_errors: yes

    - name: Criar o diretório de configuração do RustDesk
      win_file:
        path: "C:\\Users\\{{ ansible_user }}\\AppData\\Roaming\\RustDesk\\config"
        state: directory

    - name: Criar novo arquivo de configuração do RustDesk para o usuário atual
      win_template:
        src: rustdesk_config.j2
        dest: "C:\\Users\\{{ ansible_user }}\\AppData\\Roaming\\RustDesk\\config\\RustDesk2.toml"

    - name: Iniciar o serviço RustDesk
      win_service:
        name: "RustDesk"
        state: started
